#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kolor
Version  : 0.0.2
Release  : 1
URL      : https://github.com/ziggy42/kolor/archive/0.0.2.tar.gz
Source0  : https://github.com/ziggy42/kolor/archive/0.0.2.tar.gz
Source1  : https://jcenter.bintray.com/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.jar
Source2  : https://jcenter.bintray.com/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-kolor-data = %{version}-%{release}
Requires: mvn-kolor-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# kolor
[![CircleCI](https://circleci.com/gh/ziggy42/kolor.svg?style=shield)](https://circleci.com/gh/ziggy42/kolor)
[![Download](https://api.bintray.com/packages/ziggy42/kolor/kolor/images/download.svg) ](https://bintray.com/ziggy42/kolor/kolor/_latestVersion)
A library to print colored strings, with Kotlin.
(Tested on Linux only)

%package data
Summary: data components for the mvn-kolor package.
Group: Data

%description data
data components for the mvn-kolor package.


%package license
Summary: license components for the mvn-kolor package.
Group: Default

%description license
license components for the mvn-kolor package.


%prep
%setup -q -n kolor-0.0.2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-kolor
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-kolor/LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/andreapivetta/kolor/kolor/0.0.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/andreapivetta/kolor/kolor/0.0.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.jar
/usr/share/java/.m2/repository/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-kolor/LICENSE.md
